const Auth = {

    CHECK_AUTH_API: 'CHECK_AUTH_API',

    LOGOUT_USER_API: 'LOGOUT_USER_API',

    LOGIN_USER_API: 'LOGIN_USER_API',

    SIGNUP_USER_API: 'SIGNUP_USER_API',

    CHECK_LOGIN: 'CHECK_LOGIN',

    UPDATE_USER: 'UPDATE_USER',

    GET_USER_PROFILE: 'GET_USER_PROFILE',

    SET_AVAILABLE:'SET_AVAILABLE',
    
    SET_UNAVAILABLE: 'SET_UNAVAILABLE',

    FORGET_PASSWORD_USER_API: 'FORGET_PASSWORD_USER_API',

    VERIFY_OTP_CODE_USER_API: 'VERIFY_OTP_CODE_USER_API',

    RESET_PASSWORD_USER_API: 'RESET_PASSWORD_USER_API',

    REGISTER_DEVICE: 'REGISTER_DEVICE',

    GET_BIOMETRIC: 'GET_BIOMETRIC',

    CNIC: 'CNIC',
    
    BIOMETRIC: "BIOMETRIC",



};

export default Auth;