const Bookings = {

   GET_BOOKINGS:'GET_BOOKINGS',
   CHANGE_STATUS:'CHANGE_STATUS',
   CANCEL_BOOKINGS:'CANCEL_BOOKINGS',
   UPDATE_TEST_FOR_BOOKING:'UPDATE_TEST_FOR_BOOKING',
   UPDATE_PAYMENT_TYPE:'UPDATE_PAYMENT_TYPE',
   GET_SINGLE_BOOKING:'GET_SINGLE_BOOKING',
   UPDATE_TEST_FOR_APPOINTMENT:'UPDATE_TEST_FOR_APPOINTMENT',
   UPDATE_VTM:'UPDATE_VTM',
   SEND_TO_LAB: 'SEND_TO_LAB',
   CANCEL_APPOINTMENT:'CANCEL_APPOINTMENT',
};

export default Bookings;